version: "3"

volumes:
  postgresql-volume:  # pointing volume to db

services:
  mysite:
    depends_on:
      - db
    build: .
    volumes:
      - .:/mysite  # djangoapp mounted to docker from current directory
      - ./static:/static # adding static & media file for django
      - ./media:/media
    command: ./entrypoint.sh #
  db:
    image: postgres # install postgre here
    volumes:
      - postgresql-volume:/var/lib/postgresql/data # avoid data removal when shut docker down we put volume in our local
  # app:
  #   build:
  #     context: 
  #     dockerfile: Dockerfile