version: "3"

services:
  mysite:
    ports:
      - "5000:8000" # we'll use port 5000 for django
    build: .
    environment:
      - DJANGO_ENV=development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  db:
    ports:
      - "5435:5432"  # pointing port 5435 from our environment to postgre default port 5432 in docker
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'mysite'
      POSTGRES_PORT: 5432

      